### ISSUE TITLE
Update deployment instructions in README.md

### ISSUE THREAD

**Issue by slide** [jenkins-infra/ircbot#109]
The current deployment instructions for the ircbot don't seem to be correct (e.g., there is no longer a helm chart for it?). It would be good for someone with the information to update the deployment instructions area of the README.md if there is anything that needs to be done to get the updated bot deployed. If there are no longer any manual steps that need to happen, it would be good to remove the deployment instructions from the README.md

**Comment by lemeurherve** [comment]
The chart has been moved here: https://github.com/jenkins-infra/helm-charts/tree/main/charts/ircbot

Its deployed version in Jenkins Infrastructure is tracked with updatecli: https://github.com/jenkins-infra/kubernetes-management/blob/main/updatecli/updatecli.d/charts/ircbot.yaml

As other may want to deploy this tool on their own infrastructure, I think we should keep the deployment instructions. WDYT?

I'll create a PR to update the chart location.
