### ISSUE TITLE
Don't attempt deployment on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/ircbot#130]
Every build fails at the moment, because executing the build logic provided by the makefile attempts to deploy the image to the docker hub: https://ci.jenkins.io/job/Infra/job/ircbot/job/main/14/

Maybe we can outsource the logic to the Jenkinsfile and use a `isInfra()` condition to check, whether the pipeline is executed on ci.j or infra.ci.j. Depending on the result, the pipeline deploys the image to the docker hub. There's no need to attempt that on ci.j, given we can't deploy from there.

For comparison, the build succeeds on infra.ci: https://infra.ci.jenkins.io/job/docker-jobs/job/ircbot/job/main/

**Comment by lemeurherve** [comment]
I've added the repository jenkins4eval/ircbot in the docker hub, and set its permissions for the "members" group, and restarted a build, it should fix it.

**Comment by lemeurherve** [comment]
Related: https://github.com/jenkins-infra/plugin-health-scoring/issues/42

**Comment by lemeurherve** [comment]
> Finished: SUCCESS
