### ISSUE TITLE
Changing Jira component default assignee doesn't work

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/ircbot#149]
I attempted to change and remove a component's default assignee with the bot commands, but the assignee wasn't updated on Jira's end
![Screenshot 2022-10-28 at 10 45 07](https://user-images.githubusercontent.com/13383509/198545087-8f8f9eac-897e-4615-9ccc-f257fce146b4.png)
The component is still assigned to someone else, neither the person specified, nor unassigned: https://issues.jenkins.io/projects/JENKINS?selectedItem=com.atlassian.jira.jira-projects-plugin:components-page&contains=oracle-cloud-infra&isActivePressed=true

Context: https://github.com/jenkins-infra/helpdesk/issues/2497#issuecomment-1294710203

**Comment by daniel-beck** [comment]
The `ircbot` account (which I assume is used) is in the Administrators group, so rather unlikely a permissions issue.

**Comment by NotMyFault** [comment]
> The `ircbot` account (which I assume is used) is in the Administrators group, so rather unlikely a permissions issue.

Interesting and good to know. Would there be a way to obtain logs from the bot and (audit) logs from Jira covering the timeframe of someone using the command?
The bot lets you know if an operation failed, but given that didn't happen, logs could contain some hints pointing in a possible direction.

**Comment by timja** [comment]
logs contain just this:

> [main] INFO org.pircbotx.InputParser -  pircbotx.input :timja!sid405656@jenkins/contributor/timja PRIVMSG #jenkins-hosting :jenkins-admin: remove lead of token-macro-plugin
[listenerPool0-thread6546] INFO org.pircbotx.output.OutputRaw -  pircbotx.output PRIVMSG #jenkins-hosting :Changing default assignee of subcomponent token-macro-plugin to null

**Comment by NotMyFault** [comment]
Interesting, I hoped that it would fail silently and hints a _why_, but looks like commands go through fine and are handled properly? Just that nothing changes on Jira's end 🤔

**Comment by slide** [comment]
When I run the ircbot in debug mode and try and step through with the debugger, it skips past the creation of the JiraClient into the finally block, no errors are shown, not stack traces. It is very weird.

**Comment by slide** [comment]
I figured out that the issue is a NoClassDefFound which inherits from Error, not Exception, so the existing catch doesn't catch it. I created a PR that has some code cleanup and changes to catch a Throwable instead of Exception. I have a fix, but I was just blindly stabbing the issue in the dark since I am not anywhere close to a Maven or Java expert. I'll create a new PR for that tomorrow.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/jenkins-infra/ircbot/pull/151, and released in https://github.com/jenkins-infra/ircbot/releases/tag/v1.11.0

Thanks!
