### ISSUE TITLE
Adding one person to several repositories spams replies

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/ircbot#166]
![Screenshot 2022-12-14 at 17 47 30](https://user-images.githubusercontent.com/13383509/207656619-9a2df38c-f23d-433f-baa2-1c0508074616.png)

While picking up https://github.com/jenkins-infra/repository-permissions-updater/pull/3024 with the syntax outlined in the [documentation](https://www.jenkins.io/projects/infrastructure/ircbot/#github-repo-management), I wasn't able to add Mark to multiple repositories at once.

Looking at the first 2 bot responses, it appears that only one parameter is considered at a time.

No idea what happened after the third time, I guess the bot gone crazy.

**Comment by slide** [comment]
I think you just need to be patient. :) It looks like there are three instances of "Added" for each item, so I think the command was run three times since you sent it three times.

**Comment by NotMyFault** [comment]
> I think you just need to be patient. :) It looks like there are three instances of "Added" for each item, so I think the command was run three times since you sent it three times. It will say each repo individually when the user has been added.

![Screenshot 2022-12-21 at 10 29 19](https://user-images.githubusercontent.com/13383509/208871204-9ad9688c-6c0d-4d4e-9276-a49ecf08554d.png)
Absolutely, I was just too fast for the bot :P
